[package]
name = "diesel_filter"
version = "0.1.0"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>"]
edition = "2018"

[features]
serialize = ["serde"]
pagination = ["diesel"]
rocket = ["diesel_filter_query/rocket"]

[dependencies]
diesel_filter_query = { path = "../query" }
serde = { version = "1.0", optional = true }
diesel = { version = "1.4", optional = true }
